# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.deldot.com:
    container_name: orderer.deldot.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/deldot.com/orderers/orderer.deldot.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/deldot.com/orderers/orderer.deldot.com/tls/:/var/hyperledger/orderer/tls
        - orderer.deldot.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.deldot.com:
    container_name: peer0.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.deldot.com
      - CORE_PEER_ADDRESS=peer0.org1.deldot.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.deldot.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
        peer3.org1.deldot.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.deldot.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer0.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer0.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.deldot.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.deldot.com:
    container_name: peer1.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.deldot.com
      - CORE_PEER_ADDRESS=peer1.org1.deldot.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.deldot.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.deldot.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer2.org1.deldot.com:9051
        peer3.org1.deldot.com:10051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer1.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer1.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.deldot.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer2.org1.deldot.com:
    container_name: peer2.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1.deldot.com
      - CORE_PEER_ADDRESS=peer2.org1.deldot.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.deldot.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.deldot.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer3.org1.deldot.com:10051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer2.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer2.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer2.org1.deldot.com:/var/hyperledger/production

    ports:
      - 9051:9051

  peer3.org1.deldot.com:
    container_name: peer3.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org1.deldot.com
      - CORE_PEER_ADDRESS=peer3.org1.deldot.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org1.deldot.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.deldot.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer3.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer3.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer3.org1.deldot.com:/var/hyperledger/production

    ports:
      - 10051:10051

  peer4.org1.deldot.com:
    container_name: peer4.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.org1.deldot.com
      - CORE_PEER_ADDRESS=peer4.org1.deldot.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer4.org1.deldot.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1.deldot.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer4.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer4.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer4.org1.deldot.com:/var/hyperledger/production

    ports:
      - 11051:11051

  peer5.org1.deldot.com:
    container_name: peer5.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer5.org1.deldot.com
      - CORE_PEER_ADDRESS=peer5.org1.deldot.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer5.org1.deldot.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.org1.deldot.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer5.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer5.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer5.org1.deldot.com:/var/hyperledger/production

    ports:
      - 12051:12051

  peer6.org1.deldot.com:
    container_name: peer6.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer6.org1.deldot.com
      - CORE_PEER_ADDRESS=peer6.org1.deldot.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer6.org1.deldot.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer6.org1.deldot.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer6.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer6.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer6.org1.deldot.com:/var/hyperledger/production

    ports:
      - 13051:13051

  peer7.org1.deldot.com:
    container_name: peer7.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer7.org1.deldot.com
      - CORE_PEER_ADDRESS=peer7.org1.deldot.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer7.org1.deldot.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer7.org1.deldot.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer7.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer7.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer7.org1.deldot.com:/var/hyperledger/production

    ports:
      - 14051:14051

  peer8.org1.deldot.com:
    container_name: peer8.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer8.org1.deldot.com
      - CORE_PEER_ADDRESS=peer8.org1.deldot.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer8.org1.deldot.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer8.org1.deldot.com:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer8.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer8.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer8.org1.deldot.com:/var/hyperledger/production

    ports:
      - 15051:15051

  peer9.org1.deldot.com:
    container_name: peer9.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer9.org1.deldot.com
      - CORE_PEER_ADDRESS=peer9.org1.deldot.com:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer9.org1.deldot.com:16052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer9.org1.deldot.com:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer9.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer9.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer9.org1.deldot.com:/var/hyperledger/production

    ports:
      - 16051:16051

  peer10.org1.deldot.com:
    container_name: peer10.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer10.org1.deldot.com
      - CORE_PEER_ADDRESS=peer10.org1.deldot.com:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer10.org1.deldot.com:17052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:17052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer10.org1.deldot.com:17051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer10.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer10.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer10.org1.deldot.com:/var/hyperledger/production

    ports:
      - 17051:17051

  peer11.org1.deldot.com:
    container_name: peer11.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer11.org1.deldot.com
      - CORE_PEER_ADDRESS=peer11.org1.deldot.com:18051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:18051
      - CORE_PEER_CHAINCODEADDRESS=peer11.org1.deldot.com:18052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer11.org1.deldot.com:18051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer11.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer11.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer11.org1.deldot.com:/var/hyperledger/production

    ports:
      - 18051:18051


  peer12.org1.deldot.com:
    container_name: peer12.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer12.org1.deldot.com
      - CORE_PEER_ADDRESS=peer12.org1.deldot.com:19051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:19051
      - CORE_PEER_CHAINCODEADDRESS=peer12.org1.deldot.com:19052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:19052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer12.org1.deldot.com:19051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer12.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer12.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer12.org1.deldot.com:/var/hyperledger/production

    ports:
      - 19051:19051

  peer13.org1.deldot.com:
    container_name: peer13.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer13.org1.deldot.com
      - CORE_PEER_ADDRESS=peer13.org1.deldot.com:20051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:20051
      - CORE_PEER_CHAINCODEADDRESS=peer13.org1.deldot.com:20052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer13.org1.deldot.com:20051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer13.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer13.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer13.org1.deldot.com:/var/hyperledger/production

    ports:
      - 20051:20051

  peer14.org1.deldot.com:
    container_name: peer14.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer14.org1.deldot.com
      - CORE_PEER_ADDRESS=peer14.org1.deldot.com:21051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:21051
      - CORE_PEER_CHAINCODEADDRESS=peer14.org1.deldot.com:21052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:21052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer14.org1.deldot.com:21051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer14.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer14.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer14.org1.deldot.com:/var/hyperledger/production

    ports:
      - 21051:21051

  peer15.org1.deldot.com:
    container_name: peer15.org1.deldot.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer15.org1.deldot.com
      - CORE_PEER_ADDRESS=peer15.org1.deldot.com:22051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:22051
      - CORE_PEER_CHAINCODEADDRESS=peer15.org1.deldot.com:22052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:22052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer15.org1.deldot.com:22051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.deldot.com:7051
        peer1.org1.deldot.com:8051
        peer2.org1.deldot.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer15.org1.deldot.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.deldot.com/peers/peer15.org1.deldot.com/tls:/etc/hyperledger/fabric/tls
        - peer15.org1.deldot.com:/var/hyperledger/production

    ports:
      - 22051:22051